# Generated by Django 3.0.6 on 2020-05-04 23:14

from django.db import migrations, models
import django.db.models.deletion
import track.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('short_description', models.CharField(max_length=128)),
                ('long_description', models.CharField(max_length=4086)),
            ],
            bases=(track.models.BaseModel, models.Model),
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('short_description', models.CharField(max_length=128)),
                ('long_description', models.CharField(max_length=4086)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('duration_tunit', models.CharField(blank=True, choices=[('D', 'Day'), ('H', 'Hour'), ('M', 'Wednesday')], max_length=1, null=True)),
                ('end_message', models.CharField(blank=True, max_length=128, null=True)),
                ('end_confirm', models.BooleanField()),
                ('id_track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='track.Track', verbose_name='')),
            ],
            bases=(track.models.BaseModel, models.Model),
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('short_description', models.CharField(max_length=128)),
                ('long_description', models.CharField(max_length=4086)),
                ('happens_at', models.IntegerField(default=0)),
                ('happens_at_tunit', models.CharField(choices=[('D', 'Day'), ('H', 'Hour'), ('M', 'Wednesday')], default='M', max_length=1)),
                ('periodicity', models.IntegerField(blank=True, null=True)),
                ('periodicity_tunit', models.CharField(blank=True, choices=[('D', 'Day'), ('H', 'Hour'), ('M', 'Wednesday')], max_length=1, null=True)),
                ('id_segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='track.Segment', verbose_name='')),
            ],
            bases=(track.models.BaseModel, models.Model),
        ),
    ]
