# Generated by Django 3.0.6 on 2020-05-04 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='segment',
            name='end_confirm',
        ),
        migrations.RemoveField(
            model_name='segment',
            name='end_message',
        ),
    ]
